# Generated by Django 5.1 on 2024-08-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash_car', '0002_rename_location_carwash_address_alter_worker_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='workerworkday',
            name='ended_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerworkday',
            name='started_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
