# Generated by Django 5.1 on 2024-08-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash_car', '0003_rename_user_id_worker_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='washrecord',
            old_name='user',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='washrecord',
            name='date_time',
        ),
        migrations.AddField(
            model_name='washrecord',
            name='finished_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='washrecord',
            name='ordered_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='washrecord',
            name='started_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
