# Generated by Django 5.1 on 2024-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash_car', '0005_remove_carwash_work_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashworktime',
            name='day',
            field=models.TextField(choices=[('пн', 'Понедельник'), ('вт', 'Вторник'), ('ср', 'Среда'), ('чт', 'Четверг'), ('пт', 'Пятница'), ('сб', 'Суббота'), ('вс', 'Воскресенье')], max_length=2),
        ),
    ]
